#! /bin/sh

WALLPAPER=$HOME/dotfiles/wallpapers/skyfall.jpg

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill $WALLPAPER &
# wal -i $WALLPAPER
pgrep -x compton > /dev/null || compton -b --experimental-backends --config $HOME/.config/compton/bspwm/compton.conf
pgrep -x polybar > /dev/null || polybar example &
pgrep -x redshift > /dev/null || redshift &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Focus follow pointer.
bspc config focus_follows_pointer true

# Padding top
bspc config top_padding 27
